# configuration.nix
# System-level NixOS config for host "ace"
# This file is a Nix function: { config, pkgs, inputs, ... }
#   - config  -> lets you reference options set elsewhere in this config
#   - pkgs    -> gives access to the nixpkgs package set
#   - inputs  -> gives access to flake inputs (from flake.nix, e.g. other repos/packages)

{ config, pkgs, inputs, lib, ... }:

{
  imports = [
    # Machine-specific file auto-generated by `nixos-generate-config`.
    # Contains disk UUIDs, filesystem mounts, CPU microcode, etc.
    # Don't hand-write this — regenerate it on the actual install target.
    ./hardware-configuration.nix
  ];

  ##########
  # Boot
  ##########
  
  # Use systemd-boot instead of GRUB — simpler, UEFI-only.
  boot.loader.systemd-boot.enable = true;
  
  # Lets the installer write to EFI boot variables so systemd-boot can register itself.
  boot.loader.efi.canTouchEfiVariables = true;
  
  # Use the newest kernel available in nixpkgs instead of the LTS default.
  boot.kernelPackages = pkgs.linuxPackages_latest;

  ##########
  # Networking
  ##########
  
  # Machine's hostname on the network — matches the flake's host target ("ace").
  networking.hostName = "ace";
  
  # Standard GUI-friendly network management (WiFi, Ethernet).
  networking.networkmanager.enable = true;

  ##########
  # Locale / time
  ##########
  
  time.timeZone = "Asia/Amman";
  i18n.defaultLocale = "en_US.UTF-8";
  # NOTE: keyboard layout is handled separately (console/X11 keymap), not set here.

  ##########
  # Nix settings
  ##########
  
  # Flakes and the new `nix` CLI aren't enabled by default — turn them on
  # so this flake-based setup actually works.
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  
  # Allow installing non-free packages (needed for Nvidia drivers, Discord, Steam).
  nixpkgs.config.allowUnfree = true;

  ##########
  # Display / Desktop
  ##########
  
  # Still required as a dependency for some display-manager plumbing, even under Wayland.
  #services.xserver.enable = true;
  
  services.displayManager.ly.enable = true; #minimal login screen
  
  #services.displayManager.sddm = {
    #enable = true;        # SDDM as the login screen
    #wayland.enable = true; # launches a Wayland session (Hyprland) rather than X11
  #};

  programs.hyprland = {
    enable = true;         # installs and enables Hyprland itself
    xwayland.enable = true; # lets legacy X11-only apps still run inside Hyprland
	package = inputs.hyprland.packages.${pkgs.system}.hyprland;
	portalPackage = inputs.hyprland.packages.${pkgs.system}.xdg-desktop-portal-hyprland;
  };

  # The "screen share / file picker" bridge apps use to talk to a Wayland compositor.
  xdg.portal = {
    enable = true;
    #extraPortals = [ pkgs.xdg-desktop-portal-hyprland ]; # Hyprland-specific portal backend
  };

  ##########
  # Nvidia (Ada Lovelace / RTX 4070 Ti) - for future bare-metal install
  # WARNING: leave this whole block commented out / removed while testing in a VM.
  # Forcing the nvidia driver with no Nvidia GPU present will break your display.
  ##########
  
  #services.xserver.videoDrivers = [ "nvidia" ]; # actually loads the proprietary driver
  #hardware.nvidia = {
    #modesetting.enable = true;   # proper Wayland support
    #powerManagement.enable = false;
    #open = true;                 # open-source kernel modules, required for Ada Lovelace
    #nvidiaSettings = true;       # installs the nvidia-settings GUI tool
    #package = config.boot.kernelPackages.nvidiaPackages.stable;
  #};
  #hardware.graphics = {
    #enable = true;
    #enable32Bit = true; # needed so Steam/Proton (often 32-bit) can find graphics libs
  #};

  ##########
  # Audio
  ##########
  
  # Gives pipewire realtime scheduling priority so audio doesn't stutter under load.
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;            # modern audio server, replaces PulseAudio/ALSA separately
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;      # PulseAudio compatibility layer
  };

  ##########
  # User
  ##########
  
  # wheel = sudo access, networkmanager = manage networking without root,
  # video/input = hardware access for GPU/input devices
  users.users.muad = {
    isNormalUser = true;
    description = "muad";
    extraGroups = [ "networkmanager" "wheel" "video" "input" ];
	packages = with pkgs; [ tree ];
    shell = pkgs.zsh;
  };
  programs.zsh.enable = true;

  ##########
  # Gaming stack
  ##########
  
  programs.steam = {
    enable = true;
    remotePlay.openFirewall = true;      # auto-opens firewall ports for Steam Remote Play
    dedicatedServer.openFirewall = true; # auto-opens firewall ports for hosting game servers
    gamescopeSession.enable = true;      # adds Gamescope as a selectable session (scaling/FPS cap)
  };
  
  # Lets games request temporary CPU/GPU performance tuning while running.
  programs.gamemode.enable = true;

  # Flat list of everything installed system-wide, grouped by purpose.
  # Swap/add packages freely here.
  environment.systemPackages = with pkgs; [
    # Core CLI
    git
    wget
    curl
    vim
    fastfetch
    unzip

    # Wayland / Hyprland rice stack
    waybar        # status bar
    hyprpaper     # wallpaper daemon
    hypridle      # idle management
    hyprlock      # lock screen
    rofi          # app launcher
    mako          # notification daemon
    grim          # screenshot tool
    slurp         # screen area selector (used with grim)
    cliphist      # clipboard history
    wl-clipboard  # Wayland clipboard CLI
    foot          # terminal emulator
    #alacritty    # terminal emulator (backup/alt)
    thunar        # file manager

    # Theming
    papirus-icon-theme
    bibata-cursors

    # Gaming
    lutris
    heroic
    bottles
    mangohud       # in-game performance overlay
    protonup-qt    # manages custom Proton/GE versions
    vulkan-tools   # Vulkan diagnostics (vulkaninfo, vkcube)
    discord
	
	#Muad installs
	gedit #retard editor
	vlc   #video player
  ];

  # Nvidia + Wayland environment variables — tell VA-API, session type, GBM, and GLX
  # which Nvidia backend to use so hardware video decode and OpenGL/Vulkan work
  # correctly under Wayland.
  environment.sessionVariables = {
    LIBVA_VA_DRIVER_NAME = "nvidia";
    XDG_SESSION_TYPE = "wayland";
    GBM_BACKEND = "nvidia-drm";
    __GLX_VENDOR_LIBRARY_NAME = "nvidia";
  };

  fonts.packages = with pkgs; [
    # Placeholder Nerd Font — swap for Maple Mono once packaged (not in nixpkgs by
    # default; you'd need to package it yourself, like Frost-Phoenix does in pkgs/).
    nerd-fonts.iosevka
  ];

  # Compatibility pin set once at first install — tells certain services which
  # defaults to keep for backward compatibility as you upgrade the channel.
  # Don't bump this on an existing install; only set fresh for a new one.
  system.stateVersion = "26.05";
}
